name: "New Case"
description: "Create a new SOC investigation case (generates a full structured report)."
title: "[CASE] <case title>"
labels:
  - "new-case"

body:
  - type: input
    id: case_id
    attributes:
      label: Case ID (slug-friendly)
      description: "Lowercase, numbers, dashes only (e.g., phish-2025-09-28)."
      placeholder: "phish-2025-09-28"
    validations:
      required: true

  - type: input
    id: case_title
    attributes:
      label: Case Title
      placeholder: "Suspicious Phishing Email from Vendor"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Executive Summary
      description: "1–3 sentence summary of the incident, impact, and detection context."
      placeholder: "User received phishing email with malicious attachment."
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline (Key Timestamps)
      placeholder: |
        2025-09-28 10:03 — User clicked malicious link
        2025-09-28 10:05 — Alert generated in SIEM
        2025-09-28 10:15 — Host isolated

  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts / Indicators of Compromise (IOCs)
      placeholder: |
        - IP: 203.0.113.45
        - URL: http://malicious.example/
        - SHA256: abcdef1234...
        - Domain: badsite.biz

  - type: textarea
    id: analysis
    attributes:
      label: Technical Analysis
      placeholder: |
        - Observed behavior in sandbox
        - EDR logs review summary
        - SIEM query results
        - Screenshots or relevant log snippets

  - type: textarea
    id: mitigation
    attributes:
      label: Mitigation / Response Actions
      placeholder: |
        - Blocked sender in mail gateway
        - Isolated affected endpoint
        - Reset user credentials
        - Updated detection rule

  - type: textarea
    id: recommendations
    attributes:
      label: Recommendations / Next Steps
      placeholder: |
        - Hunt for similar IOCs across environment
        - Conduct phishing awareness refresh
        - Review firewall egress policies

  - type: textarea
    id: ai_assist
    attributes:
      label: AI Prompt & Response (AI Support Summary)
      description: |
        Use this section to document AI-assisted analysis or decision-making.
        Include the prompt(s) used and key insights returned by the AI.
      placeholder: |
        **Prompt:**
        "Analyze suspicious PowerShell command from SIEM alert."

        **AI Response:**
        The command downloads a remote script via Invoke-WebRequest and executes it.
        This behavior aligns with MITRE T1059 (Command and Scripting Interpreter).

  - type: input
    id: owner
    attributes:
      label: Case Owner
      value: "Ievgen Bondarenko"
