name: "New Case"
description: "Create a new SOC investigation case (generates full report)."
title: "[CASE] <case title>"
labels:
  - "new-case"

body:
  - type: input
    id: case_id
    attributes:
      label: Case ID (slug-friendly)
      description: "Lowercase, numbers, dashes only (e.g., phish-2025-09-28)."
      placeholder: "phish-2025-09-28"
    validations:
      required: true

  - type: input
    id: case_title
    attributes:
      label: Case Title
      placeholder: "Suspicious Phishing Email from Vendor"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Executive summary
      description: "1–3 sentence summary of the incident and impact."
      placeholder: "User received phishing email with malicious attachment."
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline (key timestamps)
      placeholder: "2025-09-28 10:03 — user clicked link"

  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts / IOCs
      placeholder: "- IP: 203.0.113.45\n- URL: http://bad.example/\n- SHA256: abc..."

  - type: textarea
    id: analysis
    attributes:
      label: Technical analysis
      placeholder: "Sandbox/EDR/SIEM notes..."

  - type: textarea
    id: mitigation
    attributes:
      label: Actions taken / Mitigation
      placeholder: "- Blocked sender\n- Isolated host\n- Reset creds"

  - type: textarea
    id: recommendations
    attributes:
      label: Recommendations / Next steps
      placeholder: "- Hunt for IOCs\n- Update detections"

  - type: input
    id: owner
    attributes:
      label: Case owner
      value: "Ievgen Bondarenko"
