name: "New Case"
description: "Create a new SOC case from template"
title: "[CASE] <short title>"
labels: ["new-case"]
body:
  - type: input
    id: case_id
    attributes:
      label: Case ID (slug-friendly)
      description: "Lowercase, numbers, dashes only (e.g., phish-2025-09-28)."
      placeholder: "phish-2025-09-28"
    validations:
      required: true
  - type: input
    id: case_title
    attributes:
      label: Case Title
      placeholder: "Suspicious Phishing Email from Vendor"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: "1-3 sentences overall summary."
