name: RESET-REPO
on: workflow_dispatch
permissions: { contents: write }

jobs:
  nuke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete all workflows
        run: |
          rm -rf .github/workflows/*
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "RESET: remove all workflows"
          git push

      - name: Remove self
        run: |
          git rm -f .github/workflows/_reset.yml || true
          git commit -m "Remove reset workflow" || true
          git push
