name: Archive Issue to cases

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build case folder and README
        run: |
          mkdir -p cases/case-${{ github.event.issue.number }}
          echo "# ${{ github.event.issue.title }}" > cases/case-${{ github.event.issue.number }}/README.md
          echo "" >> cases/case-${{ github.event.issue.number }}/README.md
          echo "${{ github.event.issue.body }}" >> cases/case-${{ github.event.issue.number }}/README.md

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add cases/
          git commit -m "Archive issue #${{ github.event.issue.number }}"
          git push
