name: Auto create case from issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  generate-case:
    if: >
      github.event.issue.state == 'open' &&
      contains(github.event.issue.labels.*.name, 'new-case')
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse, create branch, commit file, open PR
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';

            function grab(label) {
              // Parse markdown section:
              // ### <label>
              // <blank line>
              // <content until next ### or end>
              const re = new RegExp(`###\\s*${label}[\\s\\S]*?\\n\\n([\\s\\S]*?)(?=\\n###|$)`, 'i');
              const m = body.match(re);
              return m ? m[1].trim() : '';
            }

            const fromTitle = (issue.title || '')
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/^-+|-+$/g, '')
              .slice(0, 60);

            const id = (grab('Case ID \\(slug-friendly\\)') || fromTitle || `case-${issue.number}`)
              .toLowerCase()
              .replace(/[^a-z0-9-]/g, '-')
              .replace(/^-+|-+$/g, '');

            const title = grab('Case Title') || issue.title || id;
            const summary = grab('Summary') || '—';

            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const base  = context.payload.repository.default_branch;

            // 1) get base ref
            const { data: baseRef } = await github.rest.git.getRef({
              owner, repo, ref: `heads/${base}`
            });

            // 2) create branch (ignore 422 if it already exists)
            const headRef = `refs/heads/auto/case/${id}`;
            try {
              await github.rest.git.createRef({ owner, repo, ref: headRef, sha: baseRef.object.sha });
            } catch (e) {
              if (e.status !== 422) throw e; // branch exists — continue
            }

            // 3) prepare file content
            const content = `# ${title} (${id})\n\n## Summary\n${summary}\n`;

            // 4) get last commit on branch
            const { data: headRefData } = await github.rest.git.getRef({
              owner, repo, ref: `heads/auto/case/${id}`
            });
            const { data: lastCommit } = await github.rest.git.getCommit({
              owner, repo, commit_sha: headRefData.object.sha
            });

            // 5) create blob & tree
            const { data: blob } = await github.rest.git.createBlob({
              owner, repo,
              content: Buffer.from(content, 'utf8').toString('base64'),
              encoding: 'base64'
            });

            const { data: tree } = await github.rest.git.createTree({
              owner, repo, base_tree: lastCommit.tree.sha,
              tree: [{ path: `cases/${id}/README.md`, mode: '100644', type: 'blob', sha: blob.sha }]
            });

            // 6) commit
            const { data: newCommit } = await github.rest.git.createCommit({
              owner, repo,
              message: `Add case: ${id}`,
              tree: tree.sha,
              parents: [headRefData.object.sha],
              // optional:
              // author: { name: 'github-actions[bot]', email: '41898282+github-actions[bot]@users.noreply.github.com' },
              // committer: { name: 'github-actions[bot]', email: '41898282+github-actions[bot]@users.noreply.github.com' },
            });

            await github.rest.git.updateRef({
              owner, repo, ref: `heads/auto/case/${id}`, sha: newCommit.sha, force: false
            });

            // 7) open PR (ignore if exists)
            const prTitle = `Add case: ${title} (${id})`;
            try {
              await github.rest.pulls.create({
                owner, repo, title: prTitle, head: `auto/case/${id}`, base,
                body: `Auto-generated from issue #${issue.number}.`
              });
            } catch (e) {
              if (e.status !== 422) throw e; // PR already exists -> ok
            }
