name: Cleanup & Consolidate Reports

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Consolidate reports into /cases/2025 and rebuild README
        shell: bash
        run: |
          set -euo pipefail
          YEAR="2025"
          mkdir -p "cases/${YEAR}"

          # 1) Собираем репорты из старых структур
          while IFS= read -r -d '' dir; do
            id="$(basename "$dir")"
            target="cases/${YEAR}/${id}.md"
            if [[ -f "${dir}/REPORT.md" ]]; then
              cp "${dir}/REPORT.md" "$target"
            elif [[ -f "${dir}/README.md" ]]; then
              cp "${dir}/README.md" "$target"
            fi
          done < <(find cases -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null || true)

          # 2) Подбираем одиночные .md вне cases и .github
          shopt -s nocaseglob
          while IFS= read -r -d '' md; do
            base="$(basename "${md%.md}")"
            slug="$(echo "$base" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-_' | sed 's/[_]/-/g' | cut -c1-40)"
            [[ -z "$slug" ]] && slug="report"
            target="cases/${YEAR}/extra-${slug}.md"
            if [[ ! -f "$target" ]]; then
              cp "$md" "$target"
            fi
          done < <(find . -type f -name "*.md" \
                    ! -path "./cases/*" \
                    ! -path "./.github/*" \
                    ! -name "README.md" -print0 2>/dev/null || true)

          # 3) Пересобираем корневой README как индекс
          {
            echo "# SOC Investigations Archive"
            echo
            for y in $(ls -1 cases 2>/dev/null | sort); do
              echo "## ${y}"
              for f in $(ls -1 "cases/${y}"/*.md 2>/dev/null | sort); do
                title="$(head -n 1 "$f" | sed 's/^#\\s*//')"
                [[ -z "$title" ]] && title="$(basename "$f")"
                echo "- [${title}](${f})"
              done
              echo
            done
          } > README.md

          # 4) Мягкая очистка верхнеуровневого мусора
          rm -rf auto export 2>/dev/null || true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/cleanup-archive-${{ github.run_id }}
          title: "Cleanup: consolidate reports into /cases/2025 and rebuild README"
          commit-message: "Cleanup: consolidate reports and rebuild README"
          body: |
            Consolidates Markdown reports into **/cases/2025**, rebuilds **README.md** index,
            removes top-level junk dirs **auto/** and **export/**.
            Nothing inside **/cases/** is deleted.
          labels: maintenance
