name: Generate Case

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  create:
    if: contains(join(github.event.issue.labels.*.name, ' '), 'new-case')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Save issue to README
        env:
          NUM:  ${{ github.event.issue.number }}
          TITLE: ${{ github.event.issue.title }}
          BODY:  ${{ github.event.issue.body }}
        run: |
          DIR="cases/case-$NUM"
          mkdir -p "$DIR"
          {
            echo "# $TITLE"
            echo
            echo "$BODY"
          } > "$DIR/README.md"

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add cases/
          git commit -m "Case #${{ github.event.issue.number }} archived" || true
          git push
