name: Save Issues to Cases

on:
  issues:
    types: [opened, edited]  # при создании/правке issue

# Разрешаем воркфлоу коммитить файлы в репо
permissions:
  contents: write

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create/Update case file
        env:
          TITLE: ${{ github.event.issue.title }}
          NUM: ${{ github.event.issue.number }}
          BODY: ${{ github.event.issue.body }}
        run: |
          mkdir -p cases
          # безопасный слаг из заголовка (без пробелов/слэшей/кириллицы и т.д.)
          slug="$(echo "$TITLE" \
            | tr '[:upper:]' '[:lower:]' \
            | tr ' ' '-' \
            | sed -E 's/[^a-z0-9._-]+/-/g' \
            | sed -E 's/^-+|-+$//g')"

          file="cases/${NUM}-${slug}.md"

          {
            echo "# $TITLE"
            echo
            echo "$BODY"
            echo
            echo "_Source: issue #${NUM}_"
          } > "$file"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add cases/
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Save report from issue #${{ github.event.issue.number }}"
          git push
